In [1]:
a=('return')
print(a)

return


In [4]:
import numpy as np
a=np.array([1,2,5])
b=np.array([3,5,7])
print(a)
print(b)
print(a*b)

[1 2 5]
[3 5 7]
[ 3 10 35]


In [5]:
l1=[1,2,5]
l2=[3,5,7]
print(l1+l2)

[1, 2, 5, 3, 5, 7]


In [7]:
l1=np.array([3,76,'89'])
print(l1)

['3' '76' '89']


In [8]:
l1=[[1,2,5],[1,4,6]]
print(l1)

[[1, 2, 5], [1, 4, 6]]
